FROM busybox

ENV VBOX_URL=https://download.virtualbox.org/virtualbox

RUN VAGRANT_VERSION=$(wget -q -O - https://releases.hashicorp.com/vagrant | grep vagrant | head -1 | awk -F/ '{print $3}') \
    #&& VAGRANT_VERSION=2.2.9 \
    && VBOX_VERSION=$(wget -q -O - ${VBOX_URL} | grep [0-9]'\+'.[0-9]'\+'.[0-9]'\+'/ | tail -n 1 | awk -F "[\"\"]" '{print $2}' | awk -F/ '{print $1}') \
    #&& VBOX_VERSION=6.1.10 \
    && VBOX_PACKAGE=$(wget -q -O - https://download.virtualbox.org/virtualbox/${VBOX_VERSION} | grep exe | awk -F "[\"\"]" '{print $2}') \
    && mkdir /dload/ \
    && wget https://releases.hashicorp.com/vagrant/${VAGRANT_VERSION}/vagrant_${VAGRANT_VERSION}_x86_64.msi -P /dload/ \
    && wget https://download.virtualbox.org/virtualbox/${VBOX_VERSION}/${VBOX_PACKAGE} -P /dload/
