FROM willdockerhub/curl-wget
RUN mkdir /dload/ \
    && curl -s https://api.github.com/repos/goharbor/harbor/releases/latest \
       | grep browser_download_url \
       | grep offline-installer \
       | grep -v asc \
       | cut -d '"' -f 4 \
       | xargs wget -P /dload/
